server:
  port: 8080

spring:
  application:
    name: workflow-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db
    username: ${DB_USERNAME:workflow_user}
    password: ${DB_PASSWORD:workflow_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  level:
    com.example.workflowservice: DEBUG
    org.springframework.jdbc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always